package com.amazonaws.models.nosql;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "Store")

public class StoreDO {
    private String _UUID;
    private String _StoreName;
    private Double _StoreLatitude;
    private Double _StoreLongtitude;
    private Double _StoreDistance;
    private String _StoreHeaderImage;

    @DynamoDBHashKey(attributeName = "UUID")
    @DynamoDBAttribute(attributeName = "UUID")
    @DynamoDBAutoGeneratedKey
    public String getUUID() {
        return _UUID;
    }
    public void setUUID(final String _UUID) {
        this._UUID = _UUID;
    }

    @DynamoDBAttribute(attributeName = "StoreName")
    public String getStoreName() {
        return _StoreName;
    }
    public void setStoreName(final String _StoreName) {
        this._StoreName = _StoreName;
    }

    @DynamoDBAttribute(attributeName = "StoreLatitude")
    public Double getStoreLatitude() {
        return _StoreLatitude;
    }
    public void setStoreLatitude(final Double _StoreLatitude) {
        this._StoreLatitude = _StoreLatitude;
    }

    @DynamoDBAttribute(attributeName = "StoreLongtitude")
    public Double getStoreLongtitude() {
        return _StoreLongtitude;
    }
    public void setStoreLongtitude(final Double _StoreLongtitude) {
        this._StoreLongtitude = _StoreLongtitude;
    }

    @DynamoDBAttribute(attributeName = "StoreHeaderImage")
    public String getStoreHeaderImage() {
        return _StoreHeaderImage;
    }
    public void setStoreHeaderImage(final String _StoreHeaderImage) {
        this._StoreHeaderImage = _StoreHeaderImage;
    }

    public Double getStoreDistance() {
        return _StoreDistance;
    }
    public void setStoreDistance(final Double _StoreDistance) {
        this._StoreDistance = _StoreDistance;
    }
}
